-- Decompiled with Potassium's decompiler.

return {
    AssetName = "BaldEagle",
    Big = true,
    Huge = true,
    Pivot = Vector3.new(0, 180, 0),
    HandGrip = Vector3.new(0, 180, 0),
    IsFlying = true,
    AirHeight = 6,
    FollowAirHeight = 3,
    PerchHoverHeight = 3,
    LandDelay = 1,
    LandDuration = 0.8,
    TakeoffDuration = 0.8,
    Animations = {
        Fly = "Fly",
        Land = "Land",
        GroundIdle = "GroundIdle",
        TargetPlayer = "TargetPlayer",
        GrabPlayer = "GrabPlayer"
    },
    WanderSpeed = 10.8,
    FollowSpeed = 16.8,
    WanderPauseMin = 0.6,
    WanderPauseMax = 1.4,
    WanderWaypointCountMin = 3,
    WanderWaypointCountMax = 5,
    WanderMinSegmentLength = 10,
    WanderMaxTurnAngleDeg = 70,
    WanderHeightJitter = 2,
    PerchIntervalMin = 20,
    PerchIntervalMax = 30,
    PerchDurationMin = 5,
    PerchDurationMax = 8,
    PerchHopIntervalMin = 0.8,
    PerchHopIntervalMax = 1.5,
    PerchHopDurationMin = 0.36,
    PerchHopDurationMax = 0.52,
    PerchHopPeakMin = 0.9,
    PerchHopPeakMax = 1.1,
    OrbitChancePerSecond = 0,
    EatChancePerSecond = 0,
    Behaviors = {
        EagleDive = {
            CheckIntervalMin = 0.25,
            CheckIntervalMax = 0.5,
            ChancePerCheck = 1,
            AttackSpeed = 21.84,
            DiveRadius = 3,
            DiveRadiusBig = 4.5,
            DiveRadiusHuge = 6,
            CarryOffset = 3,
            CarryDuration = 1.5,
            CarryDurationBig = 2.25,
            CarryDurationHuge = 3,
            AscendAngleDeg = 25,
            ThrowForce = 16.25,
            ThrowUp = 10,
            GrabAnimDuration = 0.5,
            ThrowAnimDuration = 0.7,
            ChaseLegTimeout = 6,
            ShovelAggroCooldown = 20,
            Cooldown = 10,
            ShooCooldown = 15,
            Debug = false
        }
    }
};