-- Decompiled with Potassium's decompiler.

return {
    AssetName = "Bee",
    Big = true,
    Huge = true,
    Pivot = Vector3.new(0, 90, 180),
    HandGrip = Vector3.new(0, 90, 180),
    IsFlying = true,
    AlwaysFlying = true,
    AirHeight = 6,
    FollowAirHeight = 3,
    Animations = {
        Fly = "Fly"
    },
    FollowSpeed = 14,
    WanderSpeed = 9,
    FullOrientation = true,
    WanderWaypointCountMin = 3,
    WanderWaypointCountMax = 5,
    WanderMinSegmentLength = 8,
    WanderMaxTurnAngleDeg = 90,
    WanderHeightJitter = 2.5,
    WanderPathRefreshInterval = 3,
    Figure8ChancePerSecond = 0.04,
    CircleChancePerSecond = 0.03,
    PlantHoverChancePerSecond = 0,
    Figure8RadiusMin = 5,
    Figure8RadiusMax = 9,
    Figure8WaypointsPerLoop = 8,
    Figure8LoopsMin = 1,
    Figure8LoopsMax = 2,
    CircleRadiusMin = 4,
    CircleRadiusMax = 7,
    CircleWaypointsPerLoop = 6,
    CircleLoopsMin = 1,
    CircleLoopsMax = 3,
    CircleHeightJitter = 2.5,
    PlantHoverDurationMin = 4,
    PlantHoverDurationMax = 7,
    PlantHoverSpeed = 3.5,
    PlantOrbitRadiusMin = 2,
    PlantOrbitRadiusMax = 3.5,
    PlantOrbitWaypoints = 8,
    PlantOrbitLoopsMin = 1,
    PlantOrbitLoopsMax = 2,
    PlantHoverYOffset = 3,
    PlantHoverHeightJitter = 1.5,
    Behaviors = {
        DefendGarden = {
            CheckIntervalMin = 0.25,
            CheckIntervalMax = 0.5,
            ChancePerCheck = 1,
            AttackSpeed = 13.5,
            ReturnSpeed = 13.5,
            StingCooldown = 10,
            HitRadius = 3.5,
            OrbitRadius = 9,
            OrbitDuration = 0.8,
            OrbitYJitter = 1,
            OrbitYMin = -1,
            OrbitYMax = 5,
            DiveLegTimeout = 2.5,
            ReturnLegTimeout = 6,
            ReturnArriveRadius = 6,
            ShovelAggroCooldown = 10,
            Cooldown = 0
        }
    }
};