-- Decompiled with Potassium's decompiler.

return {
    AssetName = "Owl",
    Big = true,
    Huge = true,
    Pivot = Vector3.new(0, 180, 0),
    HandGrip = Vector3.new(0, 180, 0),
    IsFlying = true,
    AirHeight = 6,
    FollowAirHeight = 3,
    PerchHoverHeight = 3,
    LandDelay = 1,
    LandDuration = 0.8,
    TakeoffDuration = 0.8,
    Animations = {
        Fly = "Fly",
        Land = "Land",
        GroundIdle = "GroundIdle"
    },
    WanderSpeed = 9,
    WanderPauseMin = 0.6,
    WanderPauseMax = 1.4,
    WanderWaypointCountMin = 3,
    WanderWaypointCountMax = 5,
    WanderMinSegmentLength = 10,
    WanderMaxTurnAngleDeg = 70,
    WanderHeightJitter = 2,
    PerchDurationDayMin = 30,
    PerchDurationDayMax = 45,
    PerchIntervalDayMin = 10,
    PerchIntervalDayMax = 20,
    PerchDurationNightMin = 5,
    PerchDurationNightMax = 8,
    PerchIntervalNightMin = 40,
    PerchIntervalNightMax = 60,
    PerchHopIntervalMin = 8,
    PerchHopIntervalMax = 15,
    PerchHopDurationMin = 0.36,
    PerchHopDurationMax = 0.52,
    PerchHopPeakMin = 0.9,
    PerchHopPeakMax = 1.1,
    ImmediateGardenFaceOnLand = true,
    NightShortenPerchMin = 2,
    NightShortenPerchMax = 4,
    DayForcePerchDelayMin = 2,
    DayForcePerchDelayMax = 5,
    OrbitChancePerSecond = 0,
    EatChancePerSecond = 0
};