-- Decompiled with Potassium's decompiler.

return {
    AssetName = "ShadowDragon",
    Big = true,
    Huge = true,
    Pivot = Vector3.new(0, 0, 0),
    HandGrip = Vector3.new(0, 0, 0),
    IsFlying = true,
    AirHeight = 8,
    FollowAirHeight = 4,
    PerchHoverHeight = 3,
    LandDelay = 1,
    LandDuration = 0.8,
    TakeoffDuration = 0.8,
    FollowDistanceMult = 1.75,
    BigFollowDistanceMult = 3.15,
    HugeFollowDistanceMult = 4.5,
    BigScale = 1.5,
    HugeScale = 3,
    Animations = {
        Fly = "Fly",
        Land = "Land",
        GroundIdle = "GroundIdle",
        FlyRoar = "FlyRoar",
        GroundRoar = "GroundRoar"
    },
    WanderSpeed = 9,
    WanderPauseMin = 0.6,
    WanderPauseMax = 1.4,
    WanderWaypointCountMin = 3,
    WanderWaypointCountMax = 5,
    WanderMinSegmentLength = 10,
    WanderMaxTurnAngleDeg = 70,
    WanderHeightJitter = 2,
    FullOrientation = true,
    NeverPerch = true,
    EatChancePerSecond = 0,
    OrbitChancePerSecond = 0
};