-- Decompiled with Potassium's decompiler.

local Plants = game:GetService("ReplicatedStorage"):WaitForChild("Assets"):WaitForChild("Plants");
local SeedImages = script.SeedImages;
local _ = script.PlantImages;
local FruitImages = script.FruitImages;

return {
    {
        SeedName = "Carrot",
        PurchasePrice = 1,
        RestockShop = true,
        SeedShopDisplayOrder = 1,
        YHeight = 2,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Common",
        PrimeTime = 60,
        SeedImage = SeedImages.Carrot,
        FruitImage = FruitImages.Carrot,
        RestockValues = NumberRange.new(3, 4),
        PlantModel = Plants:WaitForChild("Carrot"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Strawberry",
        PurchasePrice = 10,
        RestockShop = true,
        SeedShopDisplayOrder = 2,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = SeedImages.Strawberry,
        FruitImage = FruitImages.Strawberry,
        RestockValues = NumberRange.new(4, 5),
        PlantModel = Plants:WaitForChild("Strawberry"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Blueberry",
        PurchasePrice = 25,
        RestockShop = true,
        SeedShopDisplayOrder = 3,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = SeedImages.Blueberry,
        FruitImage = FruitImages.Blueberry,
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Blueberry"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Tulip",
        PurchasePrice = 40,
        RestockShop = true,
        SeedShopDisplayOrder = 4,
        YHeight = 0,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Uncommon",
        PrimeTime = 60,
        SeedImage = SeedImages.Tulip,
        FruitImage = FruitImages.Tulip,
        RestockValues = NumberRange.new(3, 4),
        PlantModel = Plants:WaitForChild("Tulip"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Tomato",
        PurchasePrice = 200,
        RestockShop = true,
        SeedShopDisplayOrder = 5,
        YHeight = 1,
        RestockChance = 90,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 120,
        SeedImage = SeedImages.Tomato,
        FruitImage = FruitImages.Tomato,
        RestockValues = NumberRange.new(2, 3),
        PlantModel = Plants:WaitForChild("Tomato"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Apple",
        PurchasePrice = 400,
        RestockShop = true,
        SeedShopDisplayOrder = 6,
        YHeight = 1,
        RestockChance = 52.63,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 180,
        SeedImage = SeedImages.Apple,
        FruitImage = FruitImages.Apple,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Apple"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Bamboo",
        PurchasePrice = 700,
        RestockShop = true,
        SeedShopDisplayOrder = 7,
        YHeight = 7,
        RestockChance = 80,
        IsSingleHarvest = true,
        Rarity = "Rare",
        PrimeTime = 120,
        SeedImage = SeedImages.Bamboo,
        FruitImage = FruitImages.Bamboo,
        RestockValues = NumberRange.new(7, 11),
        PlantModel = Plants:WaitForChild("Bamboo"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Corn",
        PurchasePrice = 2500,
        RestockShop = true,
        SeedShopDisplayOrder = 8,
        YHeight = 2,
        RestockChance = 35,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages.Corn,
        FruitImage = FruitImages.Corn,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Corn"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Cactus",
        PurchasePrice = 5000,
        RestockShop = true,
        SeedShopDisplayOrder = 9,
        YHeight = 3,
        RestockChance = 16.668,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages.Cactus,
        FruitImage = FruitImages.Cactus,
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Cactus"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Pineapple",
        PurchasePrice = 10000,
        RestockShop = true,
        SeedShopDisplayOrder = 10,
        YHeight = 7,
        RestockChance = 12.501,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 300,
        SeedImage = SeedImages.Pineapple,
        FruitImage = FruitImages.Pineapple,
        RestockValues = NumberRange.new(1, 3),
        PlantModel = Plants:WaitForChild("Pineapple"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Mushroom",
        PurchasePrice = 15000,
        RestockShop = true,
        SeedShopDisplayOrder = 11,
        YHeight = 7,
        RestockChance = 9.092,
        IsSingleHarvest = true,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = SeedImages.Mushroom,
        FruitImage = FruitImages.Mushroom,
        RestockValues = NumberRange.new(2, 5),
        PlantModel = Plants:WaitForChild("Mushroom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Green Bean",
        PurchasePrice = 20000,
        RestockShop = true,
        SeedShopDisplayOrder = 12,
        YHeight = 7,
        RestockChance = 15,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = SeedImages["Green Bean"],
        FruitImage = FruitImages["Green Bean"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Green Bean"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Banana",
        PurchasePrice = 30000,
        RestockShop = true,
        SeedShopDisplayOrder = 13,
        YHeight = 2,
        RestockChance = 9,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = SeedImages.Banana,
        FruitImage = FruitImages.Banana,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Banana"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Grape",
        PurchasePrice = 50000,
        RestockShop = true,
        SeedShopDisplayOrder = 14,
        YHeight = 5,
        RestockChance = 6.668,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 420,
        SeedImage = SeedImages.Grape,
        FruitImage = FruitImages.Grape,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Grape"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Coconut",
        PurchasePrice = 140000,
        RestockShop = true,
        SeedShopDisplayOrder = 15,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = SeedImages.Coconut,
        FruitImage = FruitImages.Coconut,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Coconut"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Maple Coconut",
        ReskinOf = "Coconut",
        PurchasePrice = 140000,
        RestockShop = true,
        SeedShopDisplayOrder = 115,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = SeedImages["Maple Coconut"],
        FruitImage = FruitImages["Maple Coconut"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Coconut"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Mango",
        PurchasePrice = 300000,
        RestockShop = true,
        SeedShopDisplayOrder = 16,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = SeedImages.Mango,
        FruitImage = FruitImages.Mango,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Mango"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Rocket Pop",
        PurchasePrice = 27500,
        RestockShop = true,
        SeedShopDisplayOrder = 17,
        YHeight = 2,
        RestockChance = 7,
        IsSingleHarvest = true,
        Rarity = "Legendary",
        PrimeTime = 60,
        SeedImage = SeedImages["Rocket Pop"],
        FruitImage = FruitImages["Rocket Pop"],
        RestockValues = NumberRange.new(1, 4),
        PlantModel = Plants:WaitForChild("Rocket Pop"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Dragon Fruit",
        PurchasePrice = 120000,
        RestockShop = true,
        SeedShopDisplayOrder = 18,
        YHeight = 4,
        RestockChance = 4,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 480,
        SeedImage = SeedImages["Dragon Fruit"],
        FruitImage = FruitImages["Dragon Fruit"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Dragon Fruit"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Acorn",
        PurchasePrice = 700000,
        RestockShop = true,
        SeedShopDisplayOrder = 20,
        YHeight = 4,
        RestockChance = 2.942,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 600,
        SeedImage = SeedImages.Acorn,
        FruitImage = FruitImages.Acorn,
        RestockValues = NumberRange.new(1, 3),
        PlantModel = Plants:WaitForChild("Acorn"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Cherry",
        PurchasePrice = 1200000,
        RestockShop = true,
        SeedShopDisplayOrder = 21,
        YHeight = 2,
        RestockChance = 2.274,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 660,
        SeedImage = SeedImages.Cherry,
        FruitImage = FruitImages.Cherry,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Cherry"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Sunflower",
        PurchasePrice = 5000000,
        RestockShop = true,
        SeedShopDisplayOrder = 22,
        YHeight = 1,
        RestockChance = 1.787,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 720,
        SeedImage = SeedImages.Sunflower,
        FruitImage = FruitImages.Sunflower,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Sunflower"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Fire Fern",
        PurchasePrice = 6000000,
        RestockShop = true,
        SeedShopDisplayOrder = 23,
        YHeight = 2,
        RestockChance = 1.65,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 240,
        SeedImage = SeedImages["Fire Fern"],
        FruitImage = FruitImages["Fire Fern"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Fire Fern"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Venus Fly Trap",
        PurchasePrice = 7000000,
        RestockShop = true,
        SeedShopDisplayOrder = 24,
        YHeight = 2,
        RestockChance = 1.43,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 900,
        SeedImage = SeedImages["Venus Fly Trap"],
        FruitImage = FruitImages["Venus Fly Trap"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Venus Fly Trap"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Pomegranate",
        PurchasePrice = 12000000,
        RestockShop = true,
        SeedShopDisplayOrder = 25,
        YHeight = 2,
        RestockChance = 0.927,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1200,
        SeedImage = SeedImages.Pomegranate,
        FruitImage = FruitImages.Pomegranate,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Pomegranate"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Poison Apple",
        PurchasePrice = 25000000,
        RestockShop = true,
        SeedShopDisplayOrder = 26,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1800,
        SeedImage = SeedImages["Poison Apple"],
        FruitImage = FruitImages["Poison Apple"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Poison Apple"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Venom Spitter",
        RestockShop = true,
        PurchasePrice = 30000000,
        SeedShopDisplayOrder = 27,
        YHeight = 2,
        RestockChance = 0.475,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        SeedImage = SeedImages["Venom Spitter"],
        FruitImage = FruitImages["Venom Spitter"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Venom Spitter"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Briar Rose",
        RestockShop = false,
        PurchasePrice = 50000000,
        SeedShopDisplayOrder = 28,
        YHeight = 2,
        RestockChance = 0.425,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        SeedImage = SeedImages["Briar Rose"],
        FruitImage = FruitImages["Briar Rose"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Briar Rose"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Moon Bloom",
        PurchasePrice = 85000000,
        RestockShop = true,
        SeedShopDisplayOrder = 29,
        YHeight = 0,
        RestockChance = 0.35,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Moon Bloom"],
        FruitImage = FruitImages["Moon Bloom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Moon Bloom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Sun Bloom",
        PurchasePrice = 110000000,
        RestockShop = true,
        SeedShopDisplayOrder = 30,
        YHeight = 2,
        RestockChance = 0.125,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Sun Bloom"],
        FruitImage = FruitImages["Sun Bloom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Sun Bloom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Hypno Bloom",
        PurchasePrice = 150000000,
        RestockShop = true,
        SeedShopDisplayOrder = 31,
        YHeight = 0,
        RestockChance = 0.275,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Hypno Bloom"],
        FruitImage = FruitImages["Hypno Bloom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Hypno Bloom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Dragon\'s Breath",
        PurchasePrice = 225000000,
        RestockShop = true,
        SeedShopDisplayOrder = 32,
        YHeight = 0,
        RestockChance = 0.2,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Dragon\'s Breath"],
        FruitImage = FruitImages["Dragon\'s Breath"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Dragon\'s Breath"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Star Fruit",
        PurchasePrice = 315000000,
        RestockShop = true,
        SeedShopDisplayOrder = 33,
        YHeight = 2,
        RestockChance = 0.12,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Star Fruit"],
        FruitImage = FruitImages["Star Fruit"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Star Fruit"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Ghost Pepper",
        PurchasePrice = 2800000,
        RestockShop = false,
        SeedShopDisplayOrder = 26,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1800,
        SeedImage = SeedImages["Ghost Pepper"],
        FruitImage = FruitImages["Ghost Pepper"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Ghost Pepper"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Poison Ivy",
        PurchasePrice = 2800000,
        RestockShop = false,
        SeedShopDisplayOrder = 27,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 1800,
        SeedImage = SeedImages["Poison Ivy"],
        FruitImage = FruitImages["Poison Ivy"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Poison Ivy"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Baby Cactus",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 27,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages["Baby Cactus"],
        FruitImage = FruitImages["Baby Cactus"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Baby Cactus"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Glow Mushroom",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 28,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = SeedImages["Glow Mushroom"],
        FruitImage = FruitImages["Glow Mushroom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Glow Mushroom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Romanesco",
        PurchasePrice = 2800000,
        RestockShop = false,
        SeedShopDisplayOrder = 128,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        SeedImage = SeedImages.Romanesco,
        FruitImage = FruitImages.Romanesco,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Romanesco"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Horned Melon",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 30,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages["Horned Melon"],
        FruitImage = FruitImages["Horned Melon"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Horned Melon"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Eclipse Bloom",
        PurchasePrice = 1,
        RestockShop = false,
        SeedShopDisplayOrder = 30,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Secret",
        PrimeTime = 240,
        SeedImage = SeedImages["Eclipse Bloom"],
        FruitImage = FruitImages["Eclipse Bloom"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Eclipse Bloom"),
        Worlds = { "Main" }
    },
    {
        SeedName = "Plum",
        PurchasePrice = 5000000,
        RestockShop = false,
        SeedShopDisplayOrder = 131,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 240,
        SeedImage = SeedImages.Plum,
        FruitImage = FruitImages.Plum,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Plum"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Cinnamon Stick",
        PurchasePrice = 6000000,
        RestockShop = false,
        SeedShopDisplayOrder = 132,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = SeedImages["Cinnamon Stick"],
        FruitImage = FruitImages["Cinnamon Stick"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Cinnamon Stick"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Conifer Cone",
        PurchasePrice = 40000000,
        RestockShop = true,
        SeedShopDisplayOrder = 133,
        YHeight = 2,
        RestockChance = 0.104,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        PotScale = 2.25,
        SeedImage = SeedImages["Conifer Cone"],
        FruitImage = FruitImages["Conifer Cone"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Conifer Cone"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Conifer Cone Sapling",
        PurchasePrice = 40000000,
        RestockShop = false,
        SeedShopDisplayOrder = 134,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        PotScale = 1.6,
        SeedImage = SeedImages["Conifer Cone Sapling"],
        FruitImage = FruitImages["Conifer Cone"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Conifer Cone Sapling"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Amber Cranberry",
        PurchasePrice = 140000000,
        RestockShop = true,
        SeedShopDisplayOrder = 135,
        YHeight = 2,
        RestockChance = 0.07,
        IsSingleHarvest = false,
        Rarity = "Super",
        PrimeTime = 240,
        SeedImage = SeedImages["Amber Cranberry"],
        FruitImage = FruitImages["Amber Cranberry"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Amber Cranberry"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Atlantic Giant Pumpkin",
        PurchasePrice = 600000,
        RestockShop = true,
        SeedShopDisplayOrder = 123,
        YHeight = 2,
        RestockChance = 2,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 1800,
        GrowsForever = true,
        WateringImmune = true,
        MutationImmune = true,
        SeedImage = SeedImages["Atlantic Giant Pumpkin"],
        FruitImage = FruitImages["Atlantic Giant Pumpkin"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Atlantic Giant Pumpkin"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Carrot",
        ReskinOf = "Carrot",
        PurchasePrice = 1,
        RestockShop = true,
        SeedShopDisplayOrder = 101,
        YHeight = 2,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Common",
        PrimeTime = 60,
        SeedImage = SeedImages["Maple Carrot"],
        FruitImage = FruitImages["Maple Carrot"],
        RestockValues = NumberRange.new(3, 4),
        PlantModel = Plants:WaitForChild("Maple Carrot"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Strawberry",
        ReskinOf = "Strawberry",
        PurchasePrice = 10,
        RestockShop = true,
        SeedShopDisplayOrder = 102,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = SeedImages["Maple Strawberry"],
        FruitImage = FruitImages["Maple Strawberry"],
        RestockValues = NumberRange.new(4, 5),
        PlantModel = Plants:WaitForChild("Maple Strawberry"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Blueberry",
        ReskinOf = "Blueberry",
        PurchasePrice = 25,
        RestockShop = true,
        SeedShopDisplayOrder = 103,
        YHeight = 1,
        RestockChance = 100,
        IsSingleHarvest = false,
        Rarity = "Common",
        PrimeTime = 90,
        SeedImage = SeedImages["Maple Blueberry"],
        FruitImage = FruitImages["Maple Blueberry"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Maple Blueberry"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Tulip",
        ReskinOf = "Tulip",
        PurchasePrice = 40,
        RestockShop = true,
        SeedShopDisplayOrder = 104,
        YHeight = 0,
        RestockChance = 100,
        IsSingleHarvest = true,
        Rarity = "Uncommon",
        PrimeTime = 60,
        SeedImage = SeedImages["Maple Tulip"],
        FruitImage = FruitImages["Maple Tulip"],
        RestockValues = NumberRange.new(3, 4),
        PlantModel = Plants:WaitForChild("Maple Tulip"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Tomato",
        ReskinOf = "Tomato",
        PurchasePrice = 200,
        RestockShop = true,
        SeedShopDisplayOrder = 105,
        YHeight = 1,
        RestockChance = 90,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 120,
        SeedImage = SeedImages["Maple Tomato"],
        FruitImage = FruitImages["Maple Tomato"],
        RestockValues = NumberRange.new(2, 3),
        PlantModel = Plants:WaitForChild("Maple Tomato"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Apple",
        ReskinOf = "Apple",
        PurchasePrice = 400,
        RestockShop = true,
        SeedShopDisplayOrder = 106,
        YHeight = 1,
        RestockChance = 52.63,
        IsSingleHarvest = false,
        Rarity = "Uncommon",
        PrimeTime = 180,
        SeedImage = SeedImages["Maple Apple"],
        FruitImage = FruitImages["Maple Apple"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Apple"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Bamboo",
        ReskinOf = "Bamboo",
        PurchasePrice = 700,
        RestockShop = true,
        SeedShopDisplayOrder = 107,
        YHeight = 7,
        RestockChance = 80,
        IsSingleHarvest = true,
        Rarity = "Rare",
        PrimeTime = 120,
        SeedImage = SeedImages["Maple Bamboo"],
        FruitImage = FruitImages["Maple Bamboo"],
        RestockValues = NumberRange.new(7, 11),
        PlantModel = Plants:WaitForChild("Maple Bamboo"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Corn",
        ReskinOf = "Corn",
        PurchasePrice = 2500,
        RestockShop = true,
        SeedShopDisplayOrder = 108,
        YHeight = 2,
        RestockChance = 35,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages["Maple Corn"],
        FruitImage = FruitImages["Maple Corn"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Corn"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Cactus",
        ReskinOf = "Cactus",
        PurchasePrice = 5000,
        RestockShop = true,
        SeedShopDisplayOrder = 109,
        YHeight = 3,
        RestockChance = 16.668,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages["Maple Cactus"],
        FruitImage = FruitImages["Maple Cactus"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Maple Cactus"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Pineapple",
        ReskinOf = "Pineapple",
        PurchasePrice = 10000,
        RestockShop = true,
        SeedShopDisplayOrder = 110,
        YHeight = 7,
        RestockChance = 12.501,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 300,
        SeedImage = SeedImages["Maple Pineapple"],
        FruitImage = FruitImages["Maple Pineapple"],
        RestockValues = NumberRange.new(1, 3),
        PlantModel = Plants:WaitForChild("Maple Pineapple"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Mushroom",
        ReskinOf = "Mushroom",
        PurchasePrice = 15000,
        RestockShop = true,
        SeedShopDisplayOrder = 111,
        YHeight = 7,
        RestockChance = 9.092,
        IsSingleHarvest = true,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = SeedImages["Maple Mushroom"],
        FruitImage = FruitImages["Maple Mushroom"],
        RestockValues = NumberRange.new(2, 5),
        PlantModel = Plants:WaitForChild("Maple Mushroom"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Green Bean",
        ReskinOf = "Green Bean",
        PurchasePrice = 20000,
        RestockShop = true,
        SeedShopDisplayOrder = 112,
        YHeight = 7,
        RestockChance = 15,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 360,
        SeedImage = SeedImages["Maple Green Bean"],
        FruitImage = FruitImages["Maple Green Bean"],
        RestockValues = NumberRange.new(1, 2),
        PlantModel = Plants:WaitForChild("Maple Green Bean"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Gold",
        MutationSeed = true,
        RestockShop = false,
        YHeight = 2,
        Rarity = "Legendary",
        SeedImage = SeedImages.Gold
    },
    {
        SeedName = "Rainbow",
        MutationSeed = true,
        RestockShop = false,
        YHeight = 2,
        Rarity = "Mythic",
        SeedImage = SeedImages.Rainbow
    },
    {
        SeedName = "Mega",
        MutationSeed = true,
        RestockShop = false,
        YHeight = 2,
        Rarity = "Mythic",
        SeedImage = SeedImages.Mega
    },
    {
        SeedName = "Maple Venom Spitter",
        ReskinOf = "Venom Spitter",
        RestockShop = true,
        PurchasePrice = 30000000,
        SeedShopDisplayOrder = 127,
        YHeight = 2,
        RestockChance = 0.475,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 240,
        SeedImage = SeedImages["Maple Venom Spitter"],
        FruitImage = FruitImages["Maple Venom Spitter"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Venom Spitter"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Poison Apple",
        ReskinOf = "Poison Apple",
        PurchasePrice = 25000000,
        RestockShop = true,
        SeedShopDisplayOrder = 126,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1800,
        SeedImage = SeedImages["Maple Poison Apple"],
        FruitImage = FruitImages["Maple Poison Apple"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Poison Apple"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Pomegranate",
        ReskinOf = "Pomegranate",
        PurchasePrice = 12000000,
        RestockShop = true,
        SeedShopDisplayOrder = 125,
        YHeight = 2,
        RestockChance = 0.927,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 1200,
        SeedImage = SeedImages["Maple Pomegranate"],
        FruitImage = FruitImages["Maple Pomegranate"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Pomegranate"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Venus Fly Trap",
        ReskinOf = "Venus Fly Trap",
        PurchasePrice = 7000000,
        RestockShop = true,
        SeedShopDisplayOrder = 124,
        YHeight = 2,
        RestockChance = 1.43,
        IsSingleHarvest = false,
        Rarity = "Mythic",
        PrimeTime = 900,
        SeedImage = SeedImages["Maple Venus Fly Trap"],
        FruitImage = FruitImages["Maple Venus Fly Trap"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Venus Fly Trap"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Sunflower",
        ReskinOf = "Sunflower",
        PurchasePrice = 5000000,
        RestockShop = true,
        SeedShopDisplayOrder = 122,
        YHeight = 1,
        RestockChance = 1.787,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 720,
        SeedImage = SeedImages["Maple Sunflower"],
        FruitImage = FruitImages["Maple Sunflower"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Sunflower"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Cherry",
        ReskinOf = "Cherry",
        PurchasePrice = 1200000,
        RestockShop = true,
        SeedShopDisplayOrder = 121,
        YHeight = 2,
        RestockChance = 2.274,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 660,
        SeedImage = SeedImages["Maple Cherry"],
        FruitImage = FruitImages["Maple Cherry"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Cherry"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Acorn",
        ReskinOf = "Acorn",
        PurchasePrice = 700000,
        RestockShop = true,
        SeedShopDisplayOrder = 120,
        YHeight = 4,
        RestockChance = 2.942,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 600,
        SeedImage = SeedImages["Maple Acorn"],
        FruitImage = FruitImages["Maple Acorn"],
        RestockValues = NumberRange.new(1, 3),
        PlantModel = Plants:WaitForChild("Maple Acorn"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Dragon Fruit",
        ReskinOf = "Dragon Fruit",
        PurchasePrice = 120000,
        RestockShop = true,
        SeedShopDisplayOrder = 118,
        YHeight = 4,
        RestockChance = 4,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 480,
        SeedImage = SeedImages["Maple Dragon Fruit"],
        FruitImage = FruitImages["Maple Dragon Fruit"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Dragon Fruit"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Mango",
        ReskinOf = "Mango",
        PurchasePrice = 300000,
        RestockShop = true,
        SeedShopDisplayOrder = 116,
        YHeight = 4,
        RestockChance = 5.001,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 480,
        SeedImage = SeedImages["Maple Mango"],
        FruitImage = FruitImages["Maple Mango"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Mango"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Grape",
        ReskinOf = "Grape",
        PurchasePrice = 50000,
        RestockShop = true,
        SeedShopDisplayOrder = 114,
        YHeight = 5,
        RestockChance = 6.668,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 420,
        SeedImage = SeedImages["Maple Grape"],
        FruitImage = FruitImages["Maple Grape"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Grape"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Maple Banana",
        ReskinOf = "Banana",
        PurchasePrice = 30000,
        RestockShop = true,
        SeedShopDisplayOrder = 113,
        YHeight = 2,
        RestockChance = 9,
        IsSingleHarvest = false,
        Rarity = "Epic",
        PrimeTime = 240,
        SeedImage = SeedImages["Maple Banana"],
        FruitImage = FruitImages["Maple Banana"],
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Maple Banana"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Potato",
        PurchasePrice = 500000,
        RestockShop = false,
        SeedShopDisplayOrder = 136,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Rare",
        PrimeTime = 240,
        SeedImage = SeedImages.Potato,
        FruitImage = FruitImages.Potato,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Potato"),
        Worlds = { "FallHarvest" }
    },
    {
        SeedName = "Honeysuckle",
        PurchasePrice = 2000000,
        RestockShop = false,
        SeedShopDisplayOrder = 137,
        YHeight = 2,
        RestockChance = 0.533,
        IsSingleHarvest = false,
        Rarity = "Legendary",
        PrimeTime = 240,
        SeedImage = SeedImages.Honeysuckle,
        FruitImage = FruitImages.Honeysuckle,
        RestockValues = NumberRange.new(1, 1),
        PlantModel = Plants:WaitForChild("Honeysuckle"),
        Worlds = { "FallHarvest" }
    }
};