-- Decompiled with Potassium's decompiler.

return {
    INCOME_PERCENT_PER_MINUTE = 0.6,
    MIN_TIP = 1,
    TIP_POT_FRACTION = 0.5,
    VISIT_INTERVAL_MIN = 3,
    VISIT_INTERVAL_MAX = 4.5,
    VISIT_INTERVAL_FLOOR = 1.25,
    VISIT_CONCURRENT_BASE = 3,
    MAX_CONCURRENT_VISITORS_PER_PLOT = 8,
    VISIT_DWELL_MIN = 2,
    VISIT_DWELL_MAX = 3.5,
    VISIT_WALK_SPEED = 10,
    VISIT_STAND_DISTANCE = 7,
    VISIT_VIEW_SPREAD = 2.5,
    VISITOR_SPAWN_DISTANCE_MIN = 25,
    VISITOR_SPAWN_DISTANCE_MAX = 40,
    VISIT_END_BUFFER = 1.5,
    CROWD_AREA_MARGIN = 2
};