-- Decompiled with Potassium's decompiler.

local RuntimeLib = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"));
local t = RuntimeLib.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@rbxts", "t", "lib", "ts").t;
local v1 = RuntimeLib.import(script, game:GetService("ReplicatedStorage"), "TS", "network", "ShovelNetwork");
local GlobalShovelFunctions = v1.GlobalShovelFunctions;

return {
    ShovelEvents = v1.GlobalShovelEvents:createClient({}, {
        incomingIds = { "ShovelStateChanged", "ShovelChanged", "DigSceneStart", "DigSceneProgress", "DigSceneEnd", "SurfacedItemSpawned", "SurfacedItemClaimed", "SurfacedItemReleased", "SurfacedItemRemoved" },
        incoming = {
            ShovelStateChanged = {
                { t.number, t.boolean },
                nil
            },
            ShovelChanged = {
                { t.number, t.literal(
                        "plasticShovel",
                        "woodShovel",
                        "stoneShovel",
                        "metalShovel",
                        "goldShovel",
                        "amethystShovel",
                        "titaniumShovel",
                        "cobaltShovel",
                        "carbonShovel",
                        "rubyShovel",
                        "diamondShovel"
                    ) },
                nil
            },
            DigSceneStart = {
                {
                    t.number,
                    t.literal(
                        "duck",
                        "bear",
                        "toilet",
                        "goldStatue",
                        "rustyCan",
                        "oldBoot",
                        "glassBottle",
                        "bone",
                        "bowlingBall",
                        "sword",
                        "anchor",
                        "knightsHelmet",
                        "dinoEgg",
                        "piano",
                        "diamond",
                        "dinoSkull",
                        "spoon",
                        "sunglasses",
                        "flipFlop",
                        "newspaperHat",
                        "bucket",
                        "messageInABottle",
                        "flipPhone",
                        "beachBall",
                        "pocketWatch",
                        "vase",
                        "umbrella",
                        "recordPlayer",
                        "crab",
                        "fireHydrant",
                        "guitar",
                        "chest",
                        "bicycle",
                        "axe",
                        "crown",
                        "palmTree",
                        "ruby",
                        "pharaohsMask",
                        "moaiHead",
                        "frozenMammoth",
                        "angelDuck",
                        "shipWheel",
                        "midnightDiamond",
                        "goldBars",
                        "emerald",
                        "oldTank",
                        "crashedHelicopter",
                        "nuke",
                        "giantSquid",
                        "poseidonsTrident",
                        "ufo",
                        "tRexSkeleton",
                        "krakensEye",
                        "leviathanSkull",
                        "monaLisa"
                    ),
                    t.number,
                    t.number,
                    t.optional(t.Vector3),
                    t.optional(t.boolean)
                },
                nil
            },
            DigSceneProgress = {
                { t.number, t.number },
                nil
            },
            DigSceneEnd = {
                { t.number, t.boolean },
                nil
            },
            SurfacedItemSpawned = {
                { t.interface({
                        id = t.string,
                        itemId = t.literal(
                            "duck",
                            "bear",
                            "toilet",
                            "goldStatue",
                            "rustyCan",
                            "oldBoot",
                            "glassBottle",
                            "bone",
                            "bowlingBall",
                            "sword",
                            "anchor",
                            "knightsHelmet",
                            "dinoEgg",
                            "piano",
                            "diamond",
                            "dinoSkull",
                            "spoon",
                            "sunglasses",
                            "flipFlop",
                            "newspaperHat",
                            "bucket",
                            "messageInABottle",
                            "flipPhone",
                            "beachBall",
                            "pocketWatch",
                            "vase",
                            "umbrella",
                            "recordPlayer",
                            "crab",
                            "fireHydrant",
                            "guitar",
                            "chest",
                            "bicycle",
                            "axe",
                            "crown",
                            "palmTree",
                            "ruby",
                            "pharaohsMask",
                            "moaiHead",
                            "frozenMammoth",
                            "angelDuck",
                            "shipWheel",
                            "midnightDiamond",
                            "goldBars",
                            "emerald",
                            "oldTank",
                            "crashedHelicopter",
                            "nuke",
                            "giantSquid",
                            "poseidonsTrident",
                            "ufo",
                            "tRexSkeleton",
                            "krakensEye",
                            "leviathanSkull",
                            "monaLisa"
                        ),
                        kg = t.number,
                        oneIn = t.number,
                        position = t.Vector3
                    }) },
                nil
            },
            SurfacedItemClaimed = {
                { t.string, t.number },
                nil
            },
            SurfacedItemReleased = {
                { t.interface({
                        id = t.string,
                        itemId = t.literal(
                            "duck",
                            "bear",
                            "toilet",
                            "goldStatue",
                            "rustyCan",
                            "oldBoot",
                            "glassBottle",
                            "bone",
                            "bowlingBall",
                            "sword",
                            "anchor",
                            "knightsHelmet",
                            "dinoEgg",
                            "piano",
                            "diamond",
                            "dinoSkull",
                            "spoon",
                            "sunglasses",
                            "flipFlop",
                            "newspaperHat",
                            "bucket",
                            "messageInABottle",
                            "flipPhone",
                            "beachBall",
                            "pocketWatch",
                            "vase",
                            "umbrella",
                            "recordPlayer",
                            "crab",
                            "fireHydrant",
                            "guitar",
                            "chest",
                            "bicycle",
                            "axe",
                            "crown",
                            "palmTree",
                            "ruby",
                            "pharaohsMask",
                            "moaiHead",
                            "frozenMammoth",
                            "angelDuck",
                            "shipWheel",
                            "midnightDiamond",
                            "goldBars",
                            "emerald",
                            "oldTank",
                            "crashedHelicopter",
                            "nuke",
                            "giantSquid",
                            "poseidonsTrident",
                            "ufo",
                            "tRexSkeleton",
                            "krakensEye",
                            "leviathanSkull",
                            "monaLisa"
                        ),
                        kg = t.number,
                        oneIn = t.number,
                        position = t.Vector3
                    }) },
                nil
            },
            SurfacedItemRemoved = {
                { t.string },
                nil
            }
        },
        incomingUnreliable = {},
        outgoingIds = { "SetShovelEquipped", "DigReady", "DigInput" },
        outgoingUnreliable = {},
        namespaceIds = {},
        namespaces = {}
    }),
    ShovelFunctions = GlobalShovelFunctions:createClient({}, {
        incomingIds = {},
        incoming = {},
        outgoingIds = { "GetShovelStates", "GetSurfacedItems", "BeginDig", "StopPower", "ResolveDig" },
        outgoing = {
            GetShovelStates = t.array(t.interface({
                userId = t.number,
                equipped = t.boolean,
                shovelId = t.literal(
                    "plasticShovel",
                    "woodShovel",
                    "stoneShovel",
                    "metalShovel",
                    "goldShovel",
                    "amethystShovel",
                    "titaniumShovel",
                    "cobaltShovel",
                    "carbonShovel",
                    "rubyShovel",
                    "diamondShovel"
                )
            })),
            GetSurfacedItems = t.array(t.interface({
                id = t.string,
                itemId = t.literal(
                    "duck",
                    "bear",
                    "toilet",
                    "goldStatue",
                    "rustyCan",
                    "oldBoot",
                    "glassBottle",
                    "bone",
                    "bowlingBall",
                    "sword",
                    "anchor",
                    "knightsHelmet",
                    "dinoEgg",
                    "piano",
                    "diamond",
                    "dinoSkull",
                    "spoon",
                    "sunglasses",
                    "flipFlop",
                    "newspaperHat",
                    "bucket",
                    "messageInABottle",
                    "flipPhone",
                    "beachBall",
                    "pocketWatch",
                    "vase",
                    "umbrella",
                    "recordPlayer",
                    "crab",
                    "fireHydrant",
                    "guitar",
                    "chest",
                    "bicycle",
                    "axe",
                    "crown",
                    "palmTree",
                    "ruby",
                    "pharaohsMask",
                    "moaiHead",
                    "frozenMammoth",
                    "angelDuck",
                    "shipWheel",
                    "midnightDiamond",
                    "goldBars",
                    "emerald",
                    "oldTank",
                    "crashedHelicopter",
                    "nuke",
                    "giantSquid",
                    "poseidonsTrident",
                    "ufo",
                    "tRexSkeleton",
                    "krakensEye",
                    "leviathanSkull",
                    "monaLisa"
                ),
                kg = t.number,
                oneIn = t.number,
                position = t.Vector3
            })),
            BeginDig = t.optional(t.interface({
                sessionId = t.string,
                powerStartedAt = t.number,
                surfaced = t.optional(t.interface({
                    id = t.string,
                    itemId = t.literal(
                        "duck",
                        "bear",
                        "toilet",
                        "goldStatue",
                        "rustyCan",
                        "oldBoot",
                        "glassBottle",
                        "bone",
                        "bowlingBall",
                        "sword",
                        "anchor",
                        "knightsHelmet",
                        "dinoEgg",
                        "piano",
                        "diamond",
                        "dinoSkull",
                        "spoon",
                        "sunglasses",
                        "flipFlop",
                        "newspaperHat",
                        "bucket",
                        "messageInABottle",
                        "flipPhone",
                        "beachBall",
                        "pocketWatch",
                        "vase",
                        "umbrella",
                        "recordPlayer",
                        "crab",
                        "fireHydrant",
                        "guitar",
                        "chest",
                        "bicycle",
                        "axe",
                        "crown",
                        "palmTree",
                        "ruby",
                        "pharaohsMask",
                        "moaiHead",
                        "frozenMammoth",
                        "angelDuck",
                        "shipWheel",
                        "midnightDiamond",
                        "goldBars",
                        "emerald",
                        "oldTank",
                        "crashedHelicopter",
                        "nuke",
                        "giantSquid",
                        "poseidonsTrident",
                        "ufo",
                        "tRexSkeleton",
                        "krakensEye",
                        "leviathanSkull",
                        "monaLisa"
                    ),
                    kg = t.number,
                    oneIn = t.number,
                    position = t.Vector3
                })),
                rolled = t.optional(t.interface({
                    itemId = t.literal(
                        "duck",
                        "bear",
                        "toilet",
                        "goldStatue",
                        "rustyCan",
                        "oldBoot",
                        "glassBottle",
                        "bone",
                        "bowlingBall",
                        "sword",
                        "anchor",
                        "knightsHelmet",
                        "dinoEgg",
                        "piano",
                        "diamond",
                        "dinoSkull",
                        "spoon",
                        "sunglasses",
                        "flipFlop",
                        "newspaperHat",
                        "bucket",
                        "messageInABottle",
                        "flipPhone",
                        "beachBall",
                        "pocketWatch",
                        "vase",
                        "umbrella",
                        "recordPlayer",
                        "crab",
                        "fireHydrant",
                        "guitar",
                        "chest",
                        "bicycle",
                        "axe",
                        "crown",
                        "palmTree",
                        "ruby",
                        "pharaohsMask",
                        "moaiHead",
                        "frozenMammoth",
                        "angelDuck",
                        "shipWheel",
                        "midnightDiamond",
                        "goldBars",
                        "emerald",
                        "oldTank",
                        "crashedHelicopter",
                        "nuke",
                        "giantSquid",
                        "poseidonsTrident",
                        "ufo",
                        "tRexSkeleton",
                        "krakensEye",
                        "leviathanSkull",
                        "monaLisa"
                    ),
                    kg = t.number,
                    oneIn = t.number
                })),
                difficulty = t.optional(t.interface({
                    clickPower = t.number,
                    decay = t.number
                }))
            })),
            StopPower = t.optional(t.interface({
                sessionId = t.string,
                itemId = t.literal(
                    "duck",
                    "bear",
                    "toilet",
                    "goldStatue",
                    "rustyCan",
                    "oldBoot",
                    "glassBottle",
                    "bone",
                    "bowlingBall",
                    "sword",
                    "anchor",
                    "knightsHelmet",
                    "dinoEgg",
                    "piano",
                    "diamond",
                    "dinoSkull",
                    "spoon",
                    "sunglasses",
                    "flipFlop",
                    "newspaperHat",
                    "bucket",
                    "messageInABottle",
                    "flipPhone",
                    "beachBall",
                    "pocketWatch",
                    "vase",
                    "umbrella",
                    "recordPlayer",
                    "crab",
                    "fireHydrant",
                    "guitar",
                    "chest",
                    "bicycle",
                    "axe",
                    "crown",
                    "palmTree",
                    "ruby",
                    "pharaohsMask",
                    "moaiHead",
                    "frozenMammoth",
                    "angelDuck",
                    "shipWheel",
                    "midnightDiamond",
                    "goldBars",
                    "emerald",
                    "oldTank",
                    "crashedHelicopter",
                    "nuke",
                    "giantSquid",
                    "poseidonsTrident",
                    "ufo",
                    "tRexSkeleton",
                    "krakensEye",
                    "leviathanSkull",
                    "monaLisa"
                ),
                kg = t.number,
                oneIn = t.number,
                power = t.number,
                difficulty = t.interface({
                    clickPower = t.number,
                    decay = t.number
                })
            })),
            ResolveDig = t.boolean
        },
        namespaceIds = {},
        namespaces = {}
    })
};