-- Decompiled with Potassium's decompiler.

local ReplicatedStorage = game:GetService("ReplicatedStorage");
local FastFlags = require(ReplicatedStorage.UserGenerated.FastFlags);
local Asserts = require(ReplicatedStorage.UserGenerated.Lang.Asserts);
local v1 = FastFlags.Replicated("Game.HypnoBloom.HitCooldown", Asserts.FinitePositive, 2);
local v2 = FastFlags.Replicated("Game.HypnoBloom.StunlockHitLimit", Asserts.IntegerPositive, 10);
local v3 = FastFlags.Replicated("Game.HypnoBloom.StunlockWindow", Asserts.FinitePositive, 60);
local v4 = FastFlags.Replicated("Game.HypnoBloom.StunlockCooldown", Asserts.FinitePositive, 10);
local v5 = FastFlags.Replicated("Game.HypnoBloom.HypnotizeDuration", Asserts.FinitePositive, 3);
local v6 = FastFlags.Replicated("Game.HypnoBloom.SpinSpeedDegrees", Asserts.FiniteNonNegative, 0);
local v7 = FastFlags.Replicated("Game.HypnoBloom.ShotCooldown", Asserts.FinitePositive, 1);
local v8 = FastFlags.Replicated("Game.HypnoBloom.RetargetInterval", Asserts.FinitePositive, 1);
local v9 = FastFlags.Replicated("Game.HypnoBloom.HitRadius", Asserts.FinitePositive, 6);
local v10 = FastFlags.Replicated("Game.HypnoBloom.ParticleSpeed", Asserts.FinitePositive, 35);
local v11 = FastFlags.Replicated("Game.HypnoBloom.ParticleDrag", Asserts.FiniteNonNegative, 1);
local v12 = FastFlags.Replicated("Game.HypnoBloom.ParticleLifetime", Asserts.FinitePositive, 1.7);
local v13 = FastFlags.Replicated("Game.HypnoBloom.EmitBurstCount", Asserts.IntegerPositive, 3);
local v14 = FastFlags.Replicated("Game.HypnoBloom.EmitBurstGap", Asserts.FinitePositive, 0.2);
local v15 = FastFlags.Replicated("Game.HypnoBloom.ViewRange", Asserts.FinitePositive, 35);
local v16 = FastFlags.Replicated("Game.HypnoBloom.ViewFovDegrees", Asserts.FinitePositive, 90);
local v17 = FastFlags.Replicated("Game.HypnoBloom.ViewPitchDegrees", Asserts.FiniteNonNegative, 15);
local v18 = FastFlags.Replicated("Game.HypnoBloom.RangeHeightThresholdFeet", Asserts.FiniteNonNegative, 25);
local v19 = FastFlags.Replicated("Game.HypnoBloom.RangeHeightBonusPerFoot", Asserts.FiniteNonNegative, 0.01);
local v20 = FastFlags.Replicated("Game.HypnoBloom.RangeHeightMaxBonus", Asserts.FiniteNonNegative, 0);
local v21 = FastFlags.Replicated("Game.HypnoBloom.DebugViewCone", Asserts.Boolean, false);
local v22 = FastFlags.Replicated("Game.HypnoBloom.PulseWindup", Asserts.FinitePositive, 0.5);
local v23 = FastFlags.Replicated("Game.HypnoBloom.PulseActiveDuration", Asserts.FinitePositive, 10);
local v24 = FastFlags.Replicated("Game.HypnoBloom.PulseCooldown", Asserts.FinitePositive, 45);
local v25 = FastFlags.Replicated("Game.HypnoBloom.PulseRadius", Asserts.FinitePositive, 10);
local v26 = FastFlags.Replicated("Game.HypnoBloom.PulseRadiusMax", Asserts.FinitePositive, 60);

return table.freeze({
    ViewRange = v15,
    ViewFovDegrees = v16,
    ViewPitchDegrees = v17,
    RangeHeightThresholdFeet = v18,
    RangeHeightBonusPerFoot = v19,
    RangeHeightMaxBonus = v20,
    DebugViewCone = v21,
    HitCooldown = v1,
    StunlockHitLimit = v2,
    StunlockWindow = v3,
    StunlockCooldown = v4,
    HypnotizeDuration = v5,
    SpinSpeedDegrees = v6,
    ShotCooldown = v7,
    RetargetInterval = v8,
    HitRadius = v9,
    ParticleSpeed = v10,
    ParticleDrag = v11,
    ParticleLifetime = v12,
    EmitBurstCount = v13,
    EmitBurstGap = v14,
    PulseWindup = v22,
    PulseActiveDuration = v23,
    PulseCooldown = v24,
    PulseRadius = v25,
    PulseRadiusMax = v26
});